name: slack-approval
description: Custom action to send approval request to Slack from GitHub Actions
author: varu3
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: plus
  color: green
inputs:
  payload:
    description: Override the default Slack payload (except for the approval buttons, which will be appended automatically)
    required: false
